# blocklist
branches:
  except:
  - dev-mugpy
  - docker-mugc

# safelist
branches:
  only:
  - flask-dev
language: python
# command to install dependencies
install:
  - pip install -r calciomics_flask/requirements.txt
# command to run tests
script:
  - 
